config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/attacheds/import/:id', to: 'attacheds#import', as: "attacheds_import" 
  delete '/destroy_all/:id', to: 'attacheds#destroyer', as: "destroy_all" 


  resources :contacts, only: [:create, :index]

  resources :attacheds, only: [:create, :index]
    # collection {post :create}
  # end

  resources :fail_contacts, only: [:index, :show]

 
end

app/models/fail_contact.rb
class EncryptionService
 KEY = ActiveSupport::KeyGenerator.new( 
  Rails.application.credentials[Rails.env.to_sym][:encrypt][:key_encrypt]
  ).generate_key(
    SecureRandom.random_bytes(
    ActiveSupport::MessageEncryptor.key_len
  ),
    ActiveSupport::MessageEncryptor.key_len
  ).freeze 

  private_constant :KEY

  delegate :encrypt_and_sign, :decrypt_and_verify, to: :encryptor

  def self.encrypt(value)
    result = new.encrypt_and_sign(value[0..-5])
    result += value[-4..-1]
  end

  # def self.decrypt(value)
  #   new.decrypt_and_verify(value)
  # end

  private

  def encryptor
    ActiveSupport::MessageEncryptor.new(KEY)
  end
end

class FailContact < ApplicationRecord
  belongs_to :user
  before_save  -> { self[:credit_card] = self[:credit_card][0..-5] = "XXXXXXXX"+ self[:credit_card][-4..-1]}
end

app/controllers/fail_contacts_controller.rb
class FailContactsController  < ApplicationController
  def index
    @faileds = current_user.fail_contacts.paginate(page: params[:page], per_page: 12)
  end

  def show
    @fail = current_user.fail_contacts.find(params[:id])
  end
end

app/views/fail_contacts/index.html.erb
<div>
  <div>
    <div class="container text-center">
      <h1>List failed Contact</h1>
      <div class="flickr_pagination m-4">
        <%= will_paginate @faileds, :container => false %>
      </div>

      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Contact</th>
            <th scope="col">Message</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @faileds.each do | contact |%>
          <tr>
            <th scope="row"><%= contact.id %></th>
            <td><%= contact.email %></td>
            <td><%= contact.message %></td>
            <td><%=link_to "View", fail_contact_path(contact.id), class: "btn-sm btn-warning"%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
      <div class="flickr_pagination m-4">
        <%= will_paginate @faileds, :container => false %>
      </div>

    </div>
  </div>
</div>

app/views/fail_contacts/show.html.erb
<div class="container">
  <h1>Fail contact:</h1>

  <p> fullanme:  <%= @fail.fullname%></p>
  <p> email: <%= @fail.email%></p>
  <p> birth_date: <%= @fail.birth_date%></p>
  <p> phone: <%= @fail.phone%></p>
  <p> address: <%= @fail.address%></p>
  <p> credit_card: <%= @fail.credit_card%></p>
  <p> Messages of fail: <%= @fail.message%></p>
</div>