config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/attacheds/import/:id', to: 'attacheds#import', as: "attacheds_import" 
  delete '/destroy_all/:id', to: 'attacheds#destroyer', as: "destroy_all" 


  resources :contacts, only: [:create, :index]

  resources :attacheds, only: [:create, :index]
    # collection {post :create}
  # end

  resources :fail_contacts, only: [:index, :show]

 
end

app/models/attached.rb
require 'csv'
class ContentTypeValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value.attached? && value.content_type.in?(content_types)
      value.purge if record.new_record? # Only purge the offending blob if the record is new
      record.errors.add(attribute, "is not a valid file format", options)
    end

    unless record.attached_csv.attached?
      record.errors.add(attribute, "Please attach an file CSV", options)
    end
  end

  private

  def content_types
    options.fetch(:in)
  end
end


class Attached < ApplicationRecord
  belongs_to :user
  has_one_attached :attached_csv, dependent: :destroy
  
  

  validates :name, presence: true
  validates :attached_csv, content_type: ["text/csv"]
  validates :match, presence: true
  validates :headers_csv, numericality: { only_integer: true, equal_to: 6}

  # def self.my_import(file, current_user)
  def import
      user = User.find(user_id)
      value = 0
      convert = JSON.parse match.gsub("=>", ":")
      table = CSV.parse(attached_csv.download, headers: true, header_converters: lambda { |name| convert[name] })
        
      table.each do |row| 
        @import_contacts = user.contacts.new row.to_h
        unless @import_contacts.save
          @import_failed = user.fail_contacts.new row.to_h
          @import_failed.message = @import_contacts.errors.full_messages
          @import_failed.save
        else
          value = 1
        end
      end
      if value == 1
          status = user.attacheds.find(id)
          status.status = "finish"
          status.save
        else
          status = user.attacheds.find(id)
          status.status = "failed"
          status.save
        end
     end
 end

app/controllers/attacheds_controller.rb
class AttachedsController < ApplicationController
  before_action :get_attach, only: [:import]

  def index
    @attacheds = user_attc.paginate(page: params[:page], per_page: 12)
  end


  def new
    @attached = user_attc.new
  end

  def create
    if params[:attached].nil?
      flash[:alert] = "You shoulbe attached an file, please click on choose file"
      redirect_to root_path
      return
    end
    file = set_params
    begin 
      columns = CSV.open(file.path, headers: true).read.headers.count
    rescue
    end
    @attached = user_attc.build( 
      attached_csv: set_params,
      match: params[:headers],
      name: set_params.original_filename, 
      headers_csv: columns,
      status: "Waiting" )

    if @attached.save
      redirect_to root_path
      flash[:alert] = "file attached successfully"
    else
      message = @attached.errors.full_messages
      flash[:alert] = "Something wrong happened with the file #{message}"
      redirect_to root_path
    end
  end


  def import
    ImportWorker.perform_async(params[:id])
    flash[:notice] = "Importing contacts from file.."
    redirect_to attacheds_path
  end

  def destroyer
    #delete all associations of user
    DestroyWorker.perform_async(params[:id])
    flash[:notice] = "Deleting all"
    redirect_to attacheds_path
  end


  
  private
  def set_params
    params.require(:attached).permit(:attached_csv)[:attached_csv]
  end

  def get_attach
    attch_file = Attached.find(params[:id])
  end

  def user_attc
    current_user.attacheds
  end

 end

app/views/attacheds/index.html.erb
<div>
  <div>
    <div class="container text-center">
      <h1>List attached files</h1>

            <td><%=link_to "Delete all", destroy_all_path(current_user), method: :delete, class: "btn-sm btn-info" %></td>
      <div class="flickr_pagination m-4">
        <%= will_paginate @attacheds, :container => false %>
      </div>
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">File</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @attacheds.each do | attch |%>
          <tr>
            <th scope="row"><%= attch.id %></th>
            <td><%= attch.name %></td>
            <td><%= attch.status %></td>
            <td><%=link_to "import", attacheds_import_path(attch), method: :post, class: "btn-sm btn-info" %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
      <div class="flickr_pagination m-4">
        <%= will_paginate @attacheds, :container => false %>
      </div>

    </div>
  </div>
</div>