config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/attacheds/import/:id', to: 'attacheds#import', as: "attacheds_import" 
  delete '/destroy_all/:id', to: 'attacheds#destroyer', as: "destroy_all" 


  resources :contacts, only: [:create, :index]

  resources :attacheds, only: [:create, :index]
    # collection {post :create}
  # end

  resources :fail_contacts, only: [:index, :show]

 
end

app/views/layouts/_form.html.erb
<h1>hola</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Contact Import</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Contacts", contacts_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Fail Contacts", fail_contacts_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Attached Files", attacheds_path, class: "nav-link"%>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsImport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>